# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=BasiDiDati
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/dump:/docker-entrypoint-initdb.d/


  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8080:8080